name: Pull Request
on:
  pull_request:
    branches:
      - master

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Modules
        run: yarn
      - name: Run ES Lint
        run: yarn lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Modules
        run: yarn
      - name: Build Project
        run: yarn build
